### Reshaping the data into different Array

In [3]:
import numpy as np

In [4]:
#var = np.arrange(SV:EV+-1:Up)
#                             it generate the sequence between given  integer between the given range




In [5]:
a=np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
b= np.arange(0,30)

In [7]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

### for 2D array

In [8]:
# var.reshape(r,c):        r= Rows ,c= Columns
#it will convert the 2D array to another
sonu=b.reshape(10,3)

In [9]:
sonu

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [10]:
b= np.arange(1,28)

In [11]:
b.reshape(9,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

### changing 2D into 3D

In [12]:
# var.reshape(r,c,n_v)             n_v= number of value

k=np.arange(1,9)
k

array([1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
b.reshape(3,3,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [14]:
m=np.arange(1,13)
m

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [15]:
m.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [19]:
sonu.reshape(5,3,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29]]])

In [22]:
import numpy as np

In [29]:
# np.linespace(sv,EV,bo_of_value)
# it will create specfied number of value in the given range 
np.linspace(1,7,50)

array([1.        , 1.12244898, 1.24489796, 1.36734694, 1.48979592,
       1.6122449 , 1.73469388, 1.85714286, 1.97959184, 2.10204082,
       2.2244898 , 2.34693878, 2.46938776, 2.59183673, 2.71428571,
       2.83673469, 2.95918367, 3.08163265, 3.20408163, 3.32653061,
       3.44897959, 3.57142857, 3.69387755, 3.81632653, 3.93877551,
       4.06122449, 4.18367347, 4.30612245, 4.42857143, 4.55102041,
       4.67346939, 4.79591837, 4.91836735, 5.04081633, 5.16326531,
       5.28571429, 5.40816327, 5.53061224, 5.65306122, 5.7755102 ,
       5.89795918, 6.02040816, 6.14285714, 6.26530612, 6.3877551 ,
       6.51020408, 6.63265306, 6.75510204, 6.87755102, 7.        ])

In [30]:
# np.zeres()
# it is used to create a dummy array
# 1) np.zeroes(n)
#                 it will create 1:0 array consist of zero 




In [33]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [42]:
# 2) np.zeros(r,c):
#                    it will  create 2-D array consist of zero
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [43]:
# 3) np.zeros(r,c,n_v):
#                    it will  create 2-D array consist of zero
np.zeros((2,4,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [45]:
#np.ones() :- It is used created  dummy array consist of once

#1) np.ones(n)
#2)np.ones(r,c)
#3)np.ones(r,c,n_v)

np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [48]:
np.ones((3,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [49]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])