In [3]:
# Random 
import numpy as np

In [4]:
# syntax :-  np.random.randint(SV,EV,n)
#     # it will generate random value bertween specificed limit

np.random.randint(1,5,5)

array([4, 4, 2, 3, 4], dtype=int32)

In [7]:
# np.random.rand(n) 
#it will create n number of values between 0,1
np.random.rand(5)

array([0.86411176, 0.96396434, 0.34837301, 0.87638828, 0.27787001])

In [14]:
#np.random.randn(n) 
# it will generates n number of the values from -infinity to +infinty  , but it will mostly return between -3 to +3.

np.random.randn(10)

array([-2.05045302,  0.09693127, -0.14926755,  2.22225554, -0.18029148,
       -0.08591846, -0.53655087, -1.98138905, -0.47878302,  0.38725015])

In [41]:
##  indexing 
a=np.random.randn(18)

In [42]:
a

array([ 0.62967545, -1.30360597, -0.48898341, -0.11070185, -1.59368892,
        0.35208188, -0.617383  , -1.22057945, -1.01111159,  0.08213573,
        0.70440221,  0.63685787, -0.36834964,  0.33000708, -0.1637968 ,
        0.00283298, -0.07411517, -0.42974462])

In [21]:
a[5]

np.float64(0.47141226463894037)

###  indexing

In [22]:
a[2:3:3]

array([1.699637])

In [23]:
#2D

In [43]:
a=a.reshape(6,3)

In [44]:
a

array([[ 0.62967545, -1.30360597, -0.48898341],
       [-0.11070185, -1.59368892,  0.35208188],
       [-0.617383  , -1.22057945, -1.01111159],
       [ 0.08213573,  0.70440221,  0.63685787],
       [-0.36834964,  0.33000708, -0.1637968 ],
       [ 0.00283298, -0.07411517, -0.42974462]])

In [46]:
a[-2][-1]

np.float64(-0.16379680392942675)

In [38]:
a.shape

(2, 5)

### Agrigate function 

In [54]:
# np.sum(variable) :- 
# it will give the sum of all the values of the array. 
b = np.arange(1,20)

In [55]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [56]:
sum=np.sum(b)

In [57]:
sum

np.int64(190)

In [61]:
#np.mean(n)
# it will return the mean/average value of the variable

In [62]:
np.mean(b)

np.float64(10.0)

In [63]:
# np.min(variable)
 # it will return the minium value of the array/data 

In [65]:
np.min(b)

np.int64(1)

In [66]:
np.min(a)

np.float64(-1.5936889235961642)

In [67]:
# np.max(variable)
  # it will return the maxmum value of the array.

np.max(b)

np.int64(19)

In [69]:
np.max(a)

np.float64(0.704402207950129)

In [70]:
 # Filtering :- 
 ages=np.array([
     [21,17,29,20,10,30,18,65],
     [39,22,15,18,54,20,21,16]
            ])

In [77]:
Bacha = ages[ages<18]

In [78]:
Bacha

array([17, 10, 15, 16])

In [79]:
chaca = ages[ages>18]

In [80]:
chaca

array([21, 29, 20, 30, 65, 39, 22, 54, 20, 21])

In [85]:
 budha = (ages<60) & (ages>18)
 budha

array([[ True, False,  True,  True, False,  True, False, False],
       [ True,  True, False, False,  True,  True,  True, False]])

In [88]:
budha_age_int = ages[(ages<60) & (ages>18)]
budha_age_int

array([21, 29, 20, 30, 39, 22, 54, 20, 21])

In [93]:
budha_age_int_OR = ages[(ages<60) | (ages>18)]
budha_age_int_OR


array([21, 17, 29, 20, 10, 30, 18, 65, 39, 22, 15, 18, 54, 20, 21, 16])

In [95]:
budha_age_int_OR_bool = [(ages<60) | (ages>18)]
budha_age_int_OR_bool

array([21, 17, 29, 20, 10, 30, 18, 65, 39, 22, 15, 18, 54, 20, 21, 16])

In [96]:
budha_age_int_NOT = ages[~((ages<60) | (ages>18))]
budha_age_int_NOT

array([], dtype=int64)

In [100]:
budha_age = ages[(ages<18) | (ages>60)]
budha_age

array([17, 10, 65, 15, 16])