## Numpy Day-1

In [2]:
# NUm stands for numberic or array

# PY  stands for python 

In [3]:
# we will perform two task 
# 1 creating array 
# 2 Performing Operation on array 
'''

'''

'\n\n'

In [4]:
import numpy as np

In [5]:
# to know the version  of numpy(it will return the current version of the library )
np.__version__

'2.4.2'

In [6]:
# how to create a array 
# syntax to create a array :-  np.array(collection)
a=[1,2,3,4,5]

In [7]:
b=np.array(a)

In [8]:
print('a',type(a))


a <class 'list'>


#### Data type priority 
 >str > Complex > Float > int> bool


In [9]:
a=np.array([True,False,3,7,4.5,4-3j,'hello'])

In [10]:
type(a)

numpy.ndarray

In [11]:
type(a[1])

numpy.str_

In [12]:
a=np.array([True,False,3,7,4.5,4-3j])
type(a[1])

numpy.complex128

In [13]:
a=np.array([True,False,3,7,4.5,])
type(a[1])

numpy.float64

In [14]:
a=np.array([True,False,3,7])
type(a[1])

numpy.int64

In [15]:
a=np.array([True,False])
type(a[1])

numpy.bool

#### Trying operation  in array

In [16]:
a=np.array([2,3,5,4])
b=np.array([5,8,8,5])

In [17]:
a+b

array([ 7, 11, 13,  9])

In [18]:
a-b

array([-3, -5, -3, -1])

### Types of Array

#### 1D array

In [19]:
a=np.array([1,2,5,5,7,5])

In [20]:
a

array([1, 2, 5, 5, 7, 5])

#### 2D Array

In [21]:
b=np.array([[2,3,5,4],
           [2,4,5,7]])

In [22]:
b

array([[2, 3, 5, 4],
       [2, 4, 5, 7]])

### 3D Array

In [26]:
c=np.array([
              [[1,2,3,4],[2,5,4,5]],
              [[1,4,5,7],[1,4,5,4]],
              [[1,4,5,7],[1,4,5,4]]
         ])

In [29]:
# to check the dimensition of the array 
#var.ndim
c.ndim

3

In [30]:
c

array([[[1, 2, 3, 4],
        [2, 5, 4, 5]],

       [[1, 4, 5, 7],
        [1, 4, 5, 4]],

       [[1, 4, 5, 7],
        [1, 4, 5, 4]]])